site_name: stream-zip
repo_name: uktrade/stream-zip
repo_url: https://github.com/uktrade/stream-zip
theme:
  name: tech_docs_template
  logo: assets/dit-logo.png
  favicon: assets/dit-favicon.png
  features:
    - content.code.copy
    - navigation.sections
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      toc_depth : "2"
plugins:
  - material/search
nav:
  - Introduction: 'index.md'
  - Usage:
    - Getting started: 'getting-started.md'
    - Advanced usage: 'advanced-usage.md'
    - Methods: 'methods.md'
    - Input examples: 'input-examples.md'
    - Output examples: 'output-examples.md'
    - Exceptions: 'exceptions.md'

  - Contributing:
    - How to contribute: 'contributing.md'
    - How to make a release: 'making-a-release.md'
