name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  download:
    name: Download coverage reporter
    runs-on: ubuntu-latest
    steps:
      - name: "Download coverage reporter"
        run: |
          mkdir -p ./reporter
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./reporter/cc-test-reporter
      - uses: actions/upload-artifact@v3
        with:
          name: reporter
          path: ./reporter/cc-test-reporter

  test:
    name: Run tests
    needs: download
    strategy:
      matrix:
        include:
          # 3.7.1 is the earliest Python version available in actions/setup-python
          - python-version: "3.7.1"
            os: "ubuntu-20.04"
          - python-version: "3.7"
            os: "ubuntu-latest"
          - python-version: "3.8.0"
            os: "ubuntu-20.04"
          - python-version: "3.8"
            os: "ubuntu-latest"
          - python-version: "3.9.0"
            os: "ubuntu-20.04"
          - python-version: "3.9"
            os: "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: '${{ matrix.python-version }}'
      - name: "Fetch reporter"
        uses: actions/download-artifact@v3
        with:
          name: reporter
          path: ./reporter
      - name: "Install bsdcpio"
        run: |
          ./install-libarachive.sh
      - name: "Install python dependencies"
        run: |
          pip install ".[ci]"
          chmod +x ./reporter/cc-test-reporter
      - name: "Notify code climate of pending coverage upload"
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          ./reporter/cc-test-reporter before-build
      - name: "Run tests"
        run: |
          pytest --cov
          coverage xml
          ./reporter/cc-test-reporter format-coverage --output ./coverage/${{ matrix.python-version }}.json
      - name: "Save coverage report"
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./coverage/*.json
  upload:
    name: "Upload code coverage report to Code Climate"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/download-artifact@v3
      - name: "Upload coverage"
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          ls -R
          chmod +x ./reporter/cc-test-reporter
          ./reporter/cc-test-reporter sum-coverage ./coverage/*.json -p 6
          ./reporter/cc-test-reporter upload-coverage
